name: Generate Podcast Feeds
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name : Run Geed Generator
        uses: mamarian/podcast-generator@main
    
